[package]
name = "car-bot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
car = { path = "./car" }
tokio = { version = "1.33.0", features = ["full"] }
typemap = "0.3.3"